import React, { useState, useRef } from 'react';
import { Copy, Download, RefreshCw, Plus, X, Check } from 'lucide-react';

interface GradientColor {
  id: string;
  color: string;
  position: number;
}

type GradientType = 'linear' | 'radial' | 'conic';

export default function GradientGeneratorPage() {
  const [gradientType, setGradientType] = useState<GradientType>('linear');
  const [angle, setAngle] = useState(90);
  const [colors, setColors] = useState<GradientColor[]>([
    { id: '1', color: '#667eea', position: 0 },
    { id: '2', color: '#764ba2', position: 100 }
  ]);
  const [copied, setCopied] = useState(false);
  const previewRef = useRef<HTMLDivElement>(null);

  const generateGradient = () => {
    const sortedColors = [...colors].sort((a, b) => a.position - b.position);
    const colorStops = sortedColors.map(c => `${c.color} ${c.position}%`).join(', ');
    
    switch (gradientType) {
      case 'linear':
        return `linear-gradient(${angle}deg, ${colorStops})`;
      case 'radial':
        return `radial-gradient(circle, ${colorStops})`;
      case 'conic':
        return `conic-gradient(from ${angle}deg, ${colorStops})`;
    }
  };

  const generateCSS = () => {
    return `/* CSS Gradient generated by Damabella */
.gradient {
  background: ${generateGradient()};
  width: 100%;
  height: 100%;
}

/* Alternative with vendor prefixes */
.gradient-legacy {
  background: ${generateGradient()};
  background: -webkit-${generateGradient()};
  background: -moz-${generateGradient()};
}`;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateCSS());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleDownload = () => {
    const css = generateCSS();
    const blob = new Blob([css], { type: 'text/css' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'gradient.css';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const addColor = () => {
    const newId = Date.now().toString();
    const lastPosition = colors.length > 0 ? colors[colors.length - 1].position : 0;
    setColors([...colors, { 
      id: newId, 
      color: '#' + Math.floor(Math.random()*16777215).toString(16).padStart(6, '0'), 
      position: Math.min(lastPosition + 20, 100) 
    }]);
  };

  const removeColor = (id: string) => {
    if (colors.length > 2) {
      setColors(colors.filter(c => c.id !== id));
    }
  };

  const updateColor = (id: string, color: string) => {
    setColors(colors.map(c => c.id === id ? { ...c, color } : c));
  };

  const updatePosition = (id: string, position: number) => {
    setColors(colors.map(c => c.id === id ? { ...c, position } : c));
  };

  const randomize = () => {
    const newColors = colors.map(c => ({
      ...c,
      color: '#' + Math.floor(Math.random()*16777215).toString(16).padStart(6, '0'),
      position: Math.floor(Math.random() * 100)
    }));
    setColors(newColors);
    setAngle(Math.floor(Math.random() * 360));
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 mb-2">Generador de Gradientes CSS</h1>
        <p className="text-gray-600">Crea hermosos gradientes y exporta el código CSS</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Preview Panel */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Vista Previa</h3>
          <div 
            ref={previewRef}
            className="w-full h-80 rounded-lg shadow-inner transition-all duration-300"
            style={{ background: generateGradient() }}
          />
          
          {/* Quick shapes preview */}
          <div className="mt-4 grid grid-cols-3 gap-4">
            <div 
              className="h-20 rounded-lg"
              style={{ background: generateGradient() }}
            />
            <div 
              className="h-20 rounded-full"
              style={{ background: generateGradient() }}
            />
            <div 
              className="h-20 rounded-lg"
              style={{ 
                background: `linear-gradient(135deg, ${colors[0]?.color || '#667eea'}, ${colors[colors.length - 1]?.color || '#764ba2'})`
              }}
            />
          </div>
        </div>

        {/* Controls Panel */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 space-y-6">
          {/* Gradient Type */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-3">
              Tipo de Gradiente
            </label>
            <div className="flex gap-2">
              {(['linear', 'radial', 'conic'] as GradientType[]).map((type) => (
                <button
                  key={type}
                  onClick={() => setGradientType(type)}
                  className={`flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-all ${
                    gradientType === type
                      ? 'bg-gray-900 text-white'
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  {type.charAt(0).toUpperCase() + type.slice(1)}
                </button>
              ))}
            </div>
          </div>

          {/* Angle Control */}
          {gradientType !== 'radial' && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-3">
                Ángulo: {angle}°
              </label>
              <input
                type="range"
                min="0"
                max="360"
                value={angle}
                onChange={(e) => setAngle(Number(e.target.value))}
                className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer"
              />
              <div className="flex justify-between text-xs text-gray-500 mt-1">
                <span>0°</span>
                <span>90°</span>
                <span>180°</span>
                <span>270°</span>
                <span>360°</span>
              </div>
            </div>
          )}

          {/* Colors */}
          <div>
            <div className="flex items-center justify-between mb-3">
              <label className="block text-sm font-medium text-gray-700">
                Colores
              </label>
              <button
                onClick={addColor}
                className="flex items-center gap-1 text-sm text-gray-600 hover:text-gray-900"
              >
                <Plus size={16} />
                Añadir Color
              </button>
            </div>
            <div className="space-y-3">
              {colors.map((color, index) => (
                <div key={color.id} className="flex items-center gap-3">
                  <input
                    type="color"
                    value={color.color}
                    onChange={(e) => updateColor(color.id, e.target.value)}
                    className="w-10 h-10 rounded cursor-pointer border-0"
                  />
                  <input
                    type="text"
                    value={color.color}
                    onChange={(e) => updateColor(color.id, e.target.value)}
                    className="w-24 px-2 py-1 text-sm border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-gray-500"
                    maxLength={7}
                  />
                  <input
                    type="range"
                    min="0"
                    max="100"
                    value={color.position}
                    onChange={(e) => updatePosition(color.id, Number(e.target.value))}
                    className="flex-1 h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer"
                  />
                  <span className="w-10 text-sm text-gray-600 text-right">
                    {color.position}%
                  </span>
                  {colors.length > 2 && (
                    <button
                      onClick={() => removeColor(color.id)}
                      className="p-1 text-gray-400 hover:text-red-500"
                    >
                      <X size={16} />
                    </button>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-3 pt-4 border-t border-gray-200">
            <button
              onClick={randomize}
              className="flex-1 flex items-center justify-center gap-2 py-2.5 px-4 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors"
            >
              <RefreshCw size={18} />
              Random
            </button>
            <button
              onClick={handleCopy}
              className="flex-1 flex items-center justify-center gap-2 py-2.5 px-4 bg-gray-900 text-white rounded-lg hover:bg-gray-800 transition-colors"
            >
              {copied ? <Check size={18} /> : <Copy size={18} />}
              {copied ? 'Copiado!' : 'Copiar CSS'}
            </button>
            <button
              onClick={handleDownload}
              className="flex-1 flex items-center justify-center gap-2 py-2.5 px-4 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors"
            >
              <Download size={18} />
              Descargar
            </button>
          </div>
        </div>
      </div>

      {/* CSS Output */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Código CSS Generado</h3>
        <div className="bg-gray-900 rounded-lg p-4 overflow-x-auto">
          <pre className="text-sm text-gray-100 font-mono whitespace-pre-wrap">
{generateCSS()}
          </pre>
        </div>
      </div>

      {/* Presets */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Preajustes Populares</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
          {[
            { name: 'Purple', colors: ['#667eea', '#764ba2'], angle: 135 },
            { name: 'Ocean', colors: ['#2193b0', '#6dd5ed'], angle: 135 },
            { name: 'Sunset', colors: ['#fa709a', '#fee140'], angle: 135 },
            { name: 'Forest', colors: ['#134e5e', '#71b280'], angle: 135 },
            { name: 'Fire', colors: ['#f12711', '#f5af19'], angle: 135 },
            { name: 'Night', colors: ['#0f2027', '#203a43', '#2c5364'], angle: 135 },
            { name: 'Pink', colors: ['#ec008c', '#fc6767'], angle: 135 },
            { name: 'Blue', colors: ['#1e3c72', '#2a5298'], angle: 135 },
            { name: 'Gold', colors: ['#f7971e', '#ffd200'], angle: 135 },
            { name: 'Mint', colors: ['#00b09b', '#96c93d'], angle: 135 },
            { name: 'Rose', colors: ['#ff9966', '#ff5e62'], angle: 135 },
            { name: 'Violet', colors: ['#8e2de2', '#4a00e0'], angle: 135 },
          ].map((preset) => (
            <button
              key={preset.name}
              onClick={() => {
                setColors(preset.colors.map((color, i) => ({
                  id: Date.now().toString() + i,
                  color,
                  position: i * (100 / (preset.colors.length - 1))
                })));
                setAngle(preset.angle);
              }}
              className="h-16 rounded-lg hover:ring-2 hover:ring-gray-400 transition-all"
              style={{
                background: `linear-gradient(${preset.angle}deg, ${preset.colors.join(', ')})`
              }}
              title={preset.name}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
